version: "3"

services:
  app:
    build: ./app
    command: npm start
    depends_on:
      - redis
      - postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - REDIS_PORT=6379
      - REDIS_HOST=redis
    ports:
      - "3000:3000"

  postgres:
    image: "postgres:alpine"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
    ports:
      - "5432:5432"

  redis:
    image: "redis"
    ports:
      - "6379:6379"

  nginx:
    build: ./nginx
    ports:
      - "80:80"

